name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
   build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_FIELD_065942010 }}
          app_location: "/"  # App source code path
          api_location: ""  # API source code path (optional)
          output_location: "."  # Built app content directory (optional)
          github_id_token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token for authentication
          action: "upload"  # Corrected action parameter


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request via GitHub API
        uses: actions/github-script@v6
        with:
          script: |
            const { context, core } = require('@actions/github');
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            try {
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: prNumber,
                state: 'closed' # Close the pull request
              });
              core.info(`Successfully closed PR #${prNumber}`);
            } catch (error) {
              core.setFailed(`Failed to close PR: ${error.message}`);
            }
